apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-springboot.fullname" . }}
  labels:
    {{- include "demo-springboot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tomcat
      protocol: TCP
      name: tomcat
  selector:
    {{- include "demo-springboot.selectorLabels" . | nindent 4 }}
