pipeline {
   agent { label 'docker' }

   parameters {
      string(name: 'GIT_BRANCH', defaultValue: 'master', description: 'Git branch to build')
   }

   environment {
      APP_IMAGE         = 'minhluantran017/demo-springboot'
      // Anchore server URL should be set in Global environment variables of Jenkins 
      ANCHORE_URL       = 'minhluantran017.tk/anchore'
      ANCHORE_CRED      = credentials('anchore-usrpwd-cred')
      // Artifactory URL should be set in Global environment variables of Jenkins
      ARTIFACTORY_URL   = 'http://minhluantran017.tk/artifactory'
      ARTIFACTORY_CRED  = credentials('artifactory-api-cred')
      // Docker registry URL should be set in Global environment variables of Jenkins 
      REGISTRY_URL      = 'docker.io'
      REGISTRY_CRED     = 'registry-api-cred'
      // Kubernetes kube config file
      K8S_CONFIG        = credentials("k8s-test-config-file")

      ANCHORE  = "curl -s https://ci-tools.anchore.io/inline_scan-latest | bash -s -- \
                     -u ${ANCHORE_CRED_USER} -p ${ANCHORE_CRED_PSW} -r ${ANCHORE_URL}"
      MAVEN    = "docker run -it -v ${WORKSPACE}:/app -w /app maven:3-jdk-8 mvn"
      NEWMAN   = "docker run -it -v ${WORKSPACE}/tests/functional:/test -w /test postman/newman:5-alpine newman"
      JMETER   = "docker run -it -v ${WORKSPACE}/tests/performance:/test -w /test justb4/jmeter jmeter"
      HELM     = "docker run -it -v ${WORKSPACE}/deploy/helm/demo-springboot:/app -w /app \
                  -v ${K8S_CONFIG}:/root/.kube/config alpine/helm:3-alpine helm"
   }

   options {
      timestamps()
      timeout(60)
      buildDiscarder logRotator(artifactDaysToKeepStr: '10', artifactNumToKeepStr: '100',
                                 daysToKeepStr: '30', numToKeepStr: '300')
   }

   triggers {
      cron ('0 8 * * *') // Trigger at 8am daily 
   }

   stages {
      stage('Compile') {
         steps {
            print "Compiling code..."
            script {
               env.VERSION_STRING = sh(returnStdout: true, script: 'git describe --tags --long --always --dirty').trim()
               sh """
                  ${MAVEN} clean package -DversionString=${VERSION_STRING}
                  mkdir -p artifacts
                  cp target/*.war artifacts/demo-springboot.war
               """
            }
         }
      }
      stage('Package') {
         steps {
            print "Packaging application..."
            script {
               sh """
                  docker build -f build/docker/Dockerfile . -t ${APP_IMAGE}:${VERSION_STRING}
                  docker save ${APP_IMAGE}:${VERSION_STRING} \
                     -o artifacts/demo-springboot_${VERSION_STRING}.tar
               """
            }
         }
      }
      stage('Analyze') {
         steps {
            print "Analyzing application..."
            script {
               sh "${ANCHORE} ${APP_IMAGE}:${VERSION_STRING}"
            }
         }
      }
      stage('Upload') {
         parallel {
            stage('Upload::Artifactory') {
               steps {
                  print "Uploading binaries to artifactory..."
                  dir('artifacts') {
                     sh """
                        md5sum * >> MD5SUMS.txt
                        for file in `ls .`; do
                           curl -s -X PUT -H "X-JFrog-Art-Api:${ARTIFACTORY_CRED}" -T ${file}\
                              "${ARTIFACTORY_URL}/artifacts/demo-springboot/${VERSION_STRING}/"
                        done
                     """
                  }
               }
            }
            stage('Upload::Registry') {
               steps {
                  script {
                     withDockerRegistry(credentialsId: env.REGISTRY_CRED, url: env.REGISTY_URL) {
                        print 'Uploading images to registry...'
                        sh """
                           docker push ${APP_IMAGE}:${VERSION_STRING}
                        """
                     }
                  }
               }
            }
         }
      }
      stage('Deploy') {
         steps {
            print "Deploying app to test environment..."
            script {
               print "TODO: Helm chart into test env"
               sh "${HELM} version"
            }
         }
      }
      stage('Test') {
         stages {
            stage('Test::Integration') {
               steps {
                  print 'Running integration test...'
                  script {
                     print "TODO: Run Newman API test"
                  }
               }
               post {
                  always {
                     junit allowEmptyResults: true, testResults: 'tests/integration/newman-report.xml'
                  }
               }
            }
            stage('Test::Functional') {
               steps {
                  print 'Running functional test...'
                  script {
                     print "TODO: Run Selenium test" 
                  }
               }
               post {
                  always {
                     junit allowEmptyResults: true, testResults: 'tests/functional/maven-report.xml'
                  }
               }
            }
            stage('Test::Performance') {
               steps {
                  print 'Running performance test...'
                  script {
                     print "TODO: Run JMeter test"
                  }
               }
               post {
                  always {
                     junit allowEmptyResults: true, testResults: 'tests/performance/jmeter-report.xml'
                  }
               }
            }
         }
      }
   }
   post {
      always {
         print 'Sending email to user...'
         emailext(
            subject: "[Jenkins] ${JOB_NAME} Build #${BUILD_NUMBER} - ${BUILD_RESULT}",
            body: """
               ${JOB_NAME} Build#${BUILD_NUMBER} - ${BUILD_RESULT}.\n
               Please see detail at ${BUILD_URL}.
            """,
            recipientProviders: [ requestor(), culprits() ]
         )
      }
   }
}